[build]
builder = "DOCKERFILE"
watchPatterns = ["Dockerfile", "apps/ws_server/**/*", "packages/**/*"]

[deploy]
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10

[environments.production.deploy]
numReplicas = 5

[environments.staging.deploy]
numReplicas = 2
