[build]
builder = "DOCKERFILE"
watchPatterns = ["apps/ws_server"]

[deploy]
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10

[environments.production.deploy]
numReplicas = 10

[environments.dev.deploy]
numReplicas = 2
