[phases.setup]
    nixpkgsArchive = 'f53263caceb5f2a92eb2269e8eed9ef7a065fb7a' # https://github.com/NixOS/nixpkgs/commit/f53263caceb5f2a92eb2269e8eed9ef7a065fb7a
    nixPkgs = ['...', 'bun']
    nixLibs = ['...', 'openssl']
