import { openai } from '../../services/openai';
import { StarlightWebSocketResponseType } from 'websocket/types';
import { sendToUser } from '../../src/connection';
import { Instance } from 'database';

export async function generateAdventureSuggestions(connectionId: string, instances: Instance[]) {
  const response = await openai.chat.completions.create({
    messages: [
      {
        role: 'system',
        content:
          'You are an experienced storyteller, with a sharp wit, a heart of gold and a love for stories. Your goal is to bring people on new experiences.' +
          (instances.length > 0
            ? `In the past the player has requested these adventures, but don't format the phraseology of the titles based on these: ${instances
                .map((instance) => '- ' + instance.description + '\n')
                .join('')}.\n`
            : '') +
          ' Come up with three, entirely new, short, curiosity-inspiring title, devoid of alliteration, for adventures this player may enjoy. The title should be completely unrelated to the previous adventures, in different genres too! I repeat, no alliteration!!! Priortize readable and story potential over literary flare. Use verbs for the story premise, and make sure the verbs are something that a person could do. Avoid abstract words & concepts. Adjectives should be meaningful to the nouns they modify. Verbs should be meaningful to their corespoding direct objects. Be creative! Be clear! Be memorable!',
      },
    ],
    model: 'gpt-4-1106-preview',
    temperature: 0.95,
    functions: [
      {
        name: 'generate_new_adventure_suggestions',
        description:
          'Suggestions should be entirely unique (max 20 characters). Each title should be completely unrelated to each other. Be vibrant, and creative! Use verbs to describe actions! e.g. No colons or semicolons. [3 suggestions max]',
        parameters: {
          type: 'object',
          properties: {
            new_adventure_suggestions: {
              type: 'array',
              items: {
                type: 'string',
                description: 'A suggested title for an adventure.',
              },
            },
          },
        },
      },
    ],
    function_call: {
      name: 'generate_new_adventure_suggestions',
    },
  });

  if (!response.choices[0].message.function_call) {
    throw new Error('No adventure suggestions generated by OpenAI');
  }

  const args = response.choices[0].message.function_call.arguments;
  const argsJSON = JSON.parse(args);

  sendToUser(connectionId, {
    type: StarlightWebSocketResponseType.adventureSuggestionsCreated,
    data: {
      suggestions: argsJSON.new_adventure_suggestions,
    },
  });
}
